version: '3'

services:
  service.chain:
    build:
      context: .
      dockerfile: runtime/docker/Dockerfile.seedService
    environment:
      - LOCAL_USER_ID
    volumes:
      - ./runtime/chain.seeded:/chain.seeded
      - ./runtime/Scripts:/Scripts
      - ./runtime:/runtime
    command: /Scripts/syncedMultiNode.containers.scripts/pre.up
  bs:
    build:
      context: .
      dockerfile: runtime/docker/Dockerfile.bsService
    ports:
      - "3142"
    environment:
      - LOCAL_USER_ID
    volumes:
      - ./runtime/chain.seeded:/chain.seeded
      - ./runtime/Scripts:/Scripts
      - ./runtime:/runtime
    depends_on: [service.chain]
    command: /bin/sh -c /Scripts/syncedMultiNode.containers.scripts/bs.start
  hc:
    build:
      context: .
      dockerfile: runtime/docker/Dockerfile.syncedHCMultiNode
    ports:
      - "3141"
      - "6283"
    environment:
      - LOCAL_USER_ID
    volumes:
      - ./runtime/chain.seeded:/chain.seeded
      - ./runtime/Scripts:/Scripts
      - ./runtime:/runtime
    command: /Scripts/syncedMultiNode.containers.scripts/hc.sync
    #command: /bin/sh
    depends_on: [bs]
  hc.post.up:
    build:
      context: .
      dockerfile: runtime/docker/Dockerfile.syncedHCMultiNode.releaseSyncService
    environment:
      - LOCAL_USER_ID
    volumes:
      - ./runtime/chain.seeded:/chain.seeded
      - ./runtime/Scripts:/Scripts
      - ./runtime:/runtime
    command: /Scripts/syncedMultiNode.containers.scripts/post.up
    depends_on: [hc]

# volumes:
#   seed:
